### ISSUE TITLE
Dependency update required for Docker extension 

### ISSUE THREAD

**Issue by fiveisprime** [TGRstack/vscode-extensions#1]
Hi!

I just wanted to give you a heads up that the Docker extension has been migrated to a new publisher and, you'll need to update your dependency so it will install correctly.

Please update `"PeterJausovec.vscode-docker"` to `"ms-azuretools.vscode-docker"` to ensure the extension is installed correctly.

Thanks and sorry for the inconvenience.

**Comment by Falieson** [comment]
Hey @fiveisprime  - thanks for letting me know! I'll push an update soon!

*Update 1*

- [x] used github to update the code reference
- [ ] todo: publish update to MS marketplace

**Comment by Falieson** [comment]
Hey @fiveisprime - sorry I was taking some time off. I've released version 2.2.1

- [x] used github to update the code reference
- [x] publish update to MS marketplace
